/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

// PLUGIN FILE - source.h
H_FILE_CONTENT 10 otherKey

#include <Arduino.h>
#include <tcMenu.h>

#include <tcMenuBuilder.h>
#include "Scramble.h"
#include <JoystickSwitchInput.h>
#include <RemoteMenuItem.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <EepromAbstraction.h>
#include <RemoteAuthentication.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern ArduinoAnalogDevice analogDevice;
extern char[] expOnly;
extern const GFXfont sans24p7b;

// Any externals needed by IO expanders, EEPROMs etc
extern IoAbstractionRef 123;

// Forward define the menu builder function
void buildMenu(TcMenuBuilder& builder);

// The following defines all menu item IDs.
#define MENU_EXTRA_ID  20
#define MENU_TEST_ID  1
#define MENU_ABC_ID  1043
#define MENU_OVERRIDE_SUB_NAME_ID  100
#define MENU_OVERRIDE_ANALOG2_NAME_ID  2
#define MENU_TEXT_ITEM_ID  99
#define MENU_IP_ITEM_ID  79

// Inline helper methods to access menu items
inline EnumMenuItem& getMenuExtra() { return getEnumItemById(MENU_EXTRA_ID); }
inline AnalogMenuItem& getMenuTest() { return getAnalogItemById(MENU_TEST_ID); }
inline ListRuntimeMenuItem& getMenuAbc() { return getListItemById(MENU_ABC_ID); }
inline SubMenuItem& getMenuOverrideSubName() { return getSubMenuById(MENU_OVERRIDE_SUB_NAME_ID); }
inline AnalogMenuItem& getMenuOverrideAnalog2Name() { return getAnalogItemById(MENU_OVERRIDE_ANALOG2_NAME_ID); }
inline TextMenuItem& getMenuTextItem() { return getTextItemById(MENU_TEXT_ITEM_ID); }
inline IpAddressMenuItem& getMenuIpItem() { return getIpAddressItemById(MENU_IP_ITEM_ID); }


// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return getMenuExtra(); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION callback1(int id);
void CALLBACK_FUNCTION callback2(int id);
int fnAbcRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION headerOnly(int id);

#endif // MENU_GENERATED_CODE_H
