/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for Arduino ESP32 by TcMenu 4.3.0-SNAPSHOT on 2024-03-09T11:54:47.323Z.

#include <tcMenu.h>
#include "project_menu.h"

// Each plugin's code now follows here

// PLUGIN FILE - source.cpp
CPP_FILE_CONTENT 10 otherKey

#include <Fonts/sans24p7b.h>

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "app", "4490f2fb-a48b-4c89-b6e5-7f557e5f6faf" };
AvrEeprom glAvrRom;
EepromAuthenticatorManager authManager(3);
ArduinoAnalogDevice analogDevice(42);
const int PROGMEM anotherVar;
const int PROGMEM allowedPluginVar;

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setEepromStorageMode(TC_STORE_ROM_DYNAMIC);
    menuMgr.setEepromRef(&glAvrRom);
    authManager.initialise(menuMgr.getEepromAbstraction(), 100);
    menuMgr.setAuthenticator(&authManager);
    TcMenuBuilder builder = TcMenuBuilder(&MenuManager::ROOT);
    buildMenu(builder);

    // Code generated by plugins and new operators.
        switches.initialise(io23017, true, MenuFontDef(&sans24p7b, 1), internalDigitalIo());
        switches.addSwitch(BUTTON_PIN, null);
        switches.onRelease(BUTTON_PIN, [](uint8_t /*key*/, bool held) {
                anotherFn(20);
            });
}

