/*
    Menu based sketch generated by thecoderscorner.com Menu UI Generator.
*/

#include<IoAbstraction.h>
#include<Wire.h>
#include<tcMenu.h>
[# th:each="inc : ${display.includes}"]
[(${inc})]
[/]
[# th:each="inc : ${input.inputHeaders}"]
[(${inc})]
[/]

[(${input.inputGlobals})]

// Set up the display we will use for the menu.
[(${display.globalVariables})]

/***************** Start generated menu items **********************/

// call back functions need to be declared before they are referenced - for strict compilers
[# th:each="func : ${callbacks}"]
void [(${func})](int menuId);
[/]

[# th:each="item : ${menuItems}"]
[(${item})]
[/]
/***************** End generated menu items **********************/

void setup() {
    // you can remove wire and the include if you are not using i2c components.
    Wire.begin();

    // Any additional setup steps of your own.

    // Set up the menu library with a rotary encoder and display
[(${display.setUpCode})]

[(${input.getInputSetup(firstItem)})]
}

void loop() {
    // you can do work here that you need to happen when "idle" but never
    // do anything that takes more than a few microseconds
    // start idle

    // end idle

    taskManager.runLoop();
}

/***************** Call back functions for your logic ***************/
[# th:each="func : ${callbacks}"]
void [(${func})](int menuId) {
    // TODO, your code goes here.
}

[/]
