/*
    Menu based sketch generated by thecoderscorner.com Menu UI Generator.

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE
*/

#include <tcMenu.h>
#include "[(${projectName})].h"

[(${allGlobals})]

// Export all the menu items, makes like easier for the compiler.
[# th:each="item : ${menuItems}"]
[(${item.cppText})]
[/]

void setupMenu() {
    Wire.begin(); // if you're sure you don't use wire anywhere, you can remove this line.

[(${allSetups})]
}
