/*
    Menu based sketch generated by thecoderscorner.com Menu UI Generator.
*/

#include <tcMenu.h>
#include "menuDefinition.h"

[(${allGlobals})]

// Export all the menu items, makes like easier for the compiler.
[# th:each="item : ${menuItems}"]
[(${item})]
[/]

void setupMenu(RemoteConnectorListener* listener) {
[(${allSetups})]
}
