/*
    Menu based sketch generated by thecoderscorner.com Menu UI Generator.
*/

#include <tcMenu.h>
#include "[(${projectName})].h"

[(${allGlobals})]

// Export all the menu items, makes like easier for the compiler.
[# th:each="item : ${menuItems}"]
[(${item.cppText})]
[/]

void setupMenu(ConnectorListener* listener) {
    Wire.begin(); // if you're sure you don't use wire anywhere, you can remove this line.

[(${allSetups})]
}
