#!/bin/sh
MY_PATH=$(dirname "$0")
echo TcMenu developer version from $MY_PATH
java --module-path $MY_PATH/../target/jfx/deps "-Dprism.lcdtext=false" --add-modules com.thecoderscorner.tcmenu.menuEditorUI com.thecoderscorner.menu.editorui.cli.TcMenuDesignerCmd $@
