home.dir=${HOME_DIR}

server.port=${SERVER_PORT}

# logging settings
logging.file.name=${home.dir}/prod/logs/tcmenu-web.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n