home.dir=${HOME_DIR:/Users/dave/source/temp}

server.port=8080

# logging settings
logging.file.name=${home.dir}/prod/logs/tcmenu-web.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

tcmenu.web.static-dir=${TCMENU_WEB_STATIC_DIR:/opt/tcmenu/web}