# local to source directory settings, set home dir in each environment
core.plugin.dir=${home.dir}/source/tcMenu/web-designer/tcmenu-xml-plugins
core.native.libraries.base.dir=${home.dir}/source/tcMenu/web-designer/tcMenuNative/packaged

# Limit the number of concurrent builds
tcmenu.web.generator.concurrency=2
# Max total files in request
tcmenu.web.generator.maxFiles=50
# Max single file content size (bytes) - around 1MB is more than enough for most .ino files
tcmenu.web.generator.maxFileSize=1048576
# Max total request size (for all file contents combined, etc.)
tcmenu.web.generator.maxTotalSize=5242880
# Rate limit for builds (minutes between builds per IP)
tcmenu.web.generator.rateLimitSeconds=15
