/*
 * Copyright (c)  2016-2020 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 *
 */

package com.thecoderscorner.menu.editorui.generator.core;

import com.thecoderscorner.menu.domain.CustomBuilderMenuItem;
import com.thecoderscorner.menu.domain.MenuItem;
import com.thecoderscorner.menu.domain.ScrollChoiceMenuItem;
import com.thecoderscorner.menu.domain.state.MenuTree;
import com.thecoderscorner.menu.domain.util.MenuItemHelper;
import com.thecoderscorner.menu.editorui.generator.CodeGeneratorOptions;
import com.thecoderscorner.menu.editorui.generator.EepromSaveMode;
import com.thecoderscorner.menu.editorui.generator.ProjectSaveLocation;
import com.thecoderscorner.menu.editorui.generator.arduino.CallbackRequirement;
import com.thecoderscorner.menu.editorui.generator.logger.GeneratedFile;
import com.thecoderscorner.menu.editorui.generator.logger.UserFeedbackLogger;
import com.thecoderscorner.menu.editorui.generator.parameters.CodeGeneratorCapable;
import com.thecoderscorner.menu.editorui.generator.parameters.auth.EepromAuthenticatorDefinition;
import com.thecoderscorner.menu.editorui.generator.parameters.eeprom.NoEepromDefinition;
import com.thecoderscorner.menu.editorui.generator.plugin.CodePluginItem;
import com.thecoderscorner.menu.editorui.generator.plugin.EmbeddedPlatform;
import com.thecoderscorner.menu.editorui.generator.plugin.RequiredSourceFile;
import com.thecoderscorner.menu.editorui.storage.ConfigurationStorage;
import com.thecoderscorner.menu.editorui.util.StringHelper;
import com.thecoderscorner.menu.persist.LocaleMappingHandler;
import com.thecoderscorner.menu.persist.PropertiesLocaleEnabledHandler;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.Clock;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import static com.thecoderscorner.menu.domain.CustomBuilderMenuItem.CustomMenuType.AUTHENTICATION;
import static com.thecoderscorner.menu.domain.CustomBuilderMenuItem.CustomMenuType.REMOTE_IOT_MONITOR;
import static com.thecoderscorner.menu.domain.ScrollChoiceMenuItem.ScrollChoiceMode.ARRAY_IN_EEPROM;
import static com.thecoderscorner.menu.editorui.generator.ProjectSaveLocation.*;
import static com.thecoderscorner.menu.editorui.util.StringHelper.isStringEmptyOrNull;
import static java.time.format.DateTimeFormatter.ISO_INSTANT;

public abstract class CoreCodeGenerator implements CodeGenerator {
    public static final String GENERATED_LOCAL_HEADER = "// TcMenu Generated Locale File, do not edit this file.";
    public static final String LINE_BREAK = System.lineSeparator();
    public static final String TWO_LINES = LINE_BREAK + LINE_BREAK;
    public static final String NO_REMOTE_ID = "2c101fec-1f7d-4ff3-8d2b-992ad41e7fcb";

    private static final String COMMENT_HEADER = """
            /*
                The code in this file uses open source libraries provided by thecoderscorner
                
                DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
                INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.
                
                All the variables you may need access to are marked extern in this file for easy
                use elsewhere.
             */
             
             """;

    protected final SketchFileAdjuster sketchAdjuster;
    protected final EmbeddedPlatform embeddedPlatform;
    protected final ConfigurationStorage configStore;
    protected final Clock clock;
    protected final UserFeedbackLogger feedbackLogger;
    protected MenuTree menuTree;
    protected List<String> previousPluginFiles = List.of();
    protected boolean usesProgMem;
    protected CodeConversionContext context;
    protected VariableNameGenerator namingGenerator;
    private LocaleMappingHandler localeHandler;
    protected boolean hasRemotePlugins;
    protected CodeGeneratorOptions options;
    private PluginFileProcessor fileProcessor;
    private List<RequiredSourceFile> requiredSourceFiles;
    private MenuTreeCodeGenerator menuCodeGen;
    private CodeVariableCppExtractor extractor;

    public CoreCodeGenerator(SketchFileAdjuster adjuster, EmbeddedPlatform embeddedPlatform,
                             ConfigurationStorage configStore, Clock clock,
                             UserFeedbackLogger feedbackLogger) {
        this.clock = clock;
        this.configStore = configStore;
        this.sketchAdjuster = adjuster;
        this.embeddedPlatform = embeddedPlatform;
        this.feedbackLogger = feedbackLogger;
    }

    public boolean startConversion(Path directory, List<CodePluginItem> allPlugins, MenuTree menuTree,
                                   List<String> previousPluginFiles, CodeGeneratorOptions options,
                                   LocaleMappingHandler handler, List<CreatorProperty> allProps) {
        this.menuTree = menuTree;
        this.options = options;
        this.localeHandler = handler;
        namingGenerator = new VariableNameGenerator(menuTree, options.isNamingRecursive());
        this.previousPluginFiles = previousPluginFiles;
        feedbackLogger.info("Generate %s for board %s as %s saving as %s".formatted(
                options.getApplicationName(), embeddedPlatform.getBoardId(),options.getSaveLocation(), options.getEepromSaveMode()));

        hasRemotePlugins = allPlugins.stream()
                .anyMatch(p -> p.getSubsystem() == SubSystem.REMOTE && !p.getId().equals(NO_REMOTE_ID));

        usesProgMem = embeddedPlatform.isUsesProgmem();

        try {
            doSanityChecks();

            Path srcDir = directory;
            ProjectSaveLocation psl = options.getSaveLocation();
            if (psl == ALL_TO_SRC || psl == PROJECT_TO_SRC_WITH_GENERATED) {
                srcDir = directory.resolve("src");
            }

            boolean genDir = (psl == PROJECT_TO_CURRENT_WITH_GENERATED || psl == PROJECT_TO_SRC_WITH_GENERATED);
            createTheSourceDirectoriesIfNeeded(srcDir, genDir);

            String cppFile = toSourceFile(srcDir, "_menu.cpp", genDir);
            String headerFile = toSourceFile(srcDir, "_menu.h", genDir);
            String projectName = directory.getFileName().toString();

            // Prepare the generator by initialising all the structures ready for conversion.
            menuCodeGen = makeMenuCodeGeneratorForOptions(options);
            context = new CodeConversionContext(embeddedPlatform, menuCodeGen.getFirstMenuVariable(), options, allProps);
            extractor = new CodeVariableCppExtractor(context, usesProgMem);

            allPlugins.stream().filter(CodePluginItem::isJavaPlugin)
                    .forEach(cg -> cg.getJavaImpl().beforeGenerationStarts(context));

             requiredSourceFiles = allPlugins.stream()
                    .flatMap(pi -> pi.getRequiredSourceFiles().stream())
                    .filter(i -> i.getApplicability().isApplicable(context.getProperties()))
                    .toList();

            // generate the source by first generating the CPP and H for the menu definition and then
            // update the sketch. Also, if any plugins have changed, then update them.
            Map<MenuItem, CallbackRequirement> callbackFunctions = callBackFunctions(menuTree);
            fileProcessor = createPluginFileProcessor(psl, headerFile, cppFile);
            generateHeaders(allPlugins, headerFile, menuCodeGen, extractor, projectName, callbackFunctions);
            generateSource(allPlugins, cppFile, menuCodeGen, projectName, extractor, callbackFunctions);
            fileProcessor.dealWithRequiredPlugins(allPlugins, srcDir, directory, psl, previousPluginFiles);

            if (localeHandler.isLocalSupportEnabled()) {
                processLocale(srcDir, genDir);
            }

            internalConversion(directory, srcDir, callbackFunctions, projectName);

            feedbackLogger.info("Process has completed, make sure the code in your IDE is up-to-date.");
            feedbackLogger.info("You may need to close the project and then re-open it to pick up changes..");
        } catch (Exception e) {
            feedbackLogger.error("ERROR during conversion---------------------------------------------");
            feedbackLogger.error("The conversion process has failed with an error that is listed below: ");
            feedbackLogger.error(e.getMessage());
            feedbackLogger.error("A more complete error can be found in the log file in <Home>/.tcMenu");
            feedbackLogger.error("Exception caught while converting code: ", e);
        }

        return true;
    }

    private PluginFileProcessor createPluginFileProcessor(ProjectSaveLocation psl, String headerFile, String cppFile) {
        if(psl == ONE_SINGLE_FILE || psl == ONE_SINGLE_FILE_MENU_MAIN) {
            return new AllInOnePluginFileProcessor(context, feedbackLogger, Path.of(headerFile), Path.of(cppFile));
        } else {
            return new PluginRequiredFileProcessor(context, feedbackLogger, psl, requiredSourceFiles);
        }
    }

    private MenuTreeCodeGenerator makeMenuCodeGeneratorForOptions(CodeGeneratorOptions options) throws TcMenuConversionException {
        MenuTreeCodeGenerator gen;
        if(options.isUseDynamicMenus()) {
            boolean dynamicRom = options.getEepromSaveMode() == EepromSaveMode.DYNAMIC_WRITE_BY_ID;
            gen = new MenuBuilderTreeCodeGeneratorImpl("builder", dynamicRom, namingGenerator, feedbackLogger);
        } else {
            gen = new StaticMenuTreeCodeGeneratorImpl(namingGenerator, localeHandler, feedbackLogger);
        }
        gen.initialise(menuTree);
        return gen;
    }

    private void processLocale(Path srcDir, boolean generated) throws IOException {
        feedbackLogger.debug("Starting locale processing");
        StringBuilder langSelectText = new StringBuilder(8192);
        langSelectText.append(GENERATED_LOCAL_HEADER).append(LINE_BREAK);
        langSelectText.append("// This is the header to include. Set TC_LOCAL_?? to a locale").append(LINE_BREAK);
        langSelectText.append("// or omit for the default language").append(TWO_LINES);

        var previousLocale = localeHandler.getCurrentLocale();

        try {
            String defaultLocaleFile = toSourceFile(srcDir, "_lang" + ".h", generated);
            localeHandler.changeLocale(PropertiesLocaleEnabledHandler.DEFAULT_LOCALE);
            var defaultLocaleMap = localeHandler.getUnderlyingMap();
            localeToCpp(defaultLocaleFile, PropertiesLocaleEnabledHandler.DEFAULT_LOCALE, defaultLocaleMap);
            boolean useElIf = false;

            for (var locale : localeHandler.getEnabledLocales().stream().filter(l -> !l.getLanguage().isEmpty()).toList()) {
                String localeFile = toSourceFile(srcDir, "_lang_" + locale.toString() + ".h", generated);
                localeToCpp(localeFile, locale, defaultLocaleMap);

                if (useElIf) {
                    langSelectText.append("#elif");
                } else {
                    langSelectText.append("#if");
                    useElIf = true;
                }
                langSelectText.append(" defined(TC_LOCALE_").append(locale.toString().toUpperCase()).append(')')
                        .append(LINE_BREAK);
                langSelectText.append("# include \"").append(Paths.get(localeFile).getFileName()).append("\"").append(LINE_BREAK);
            }

            Path defPath = Paths.get(defaultLocaleFile);
            if (useElIf) {
                langSelectText.append("#else").append(LINE_BREAK).append("#include \"")
                        .append(defPath.getFileName()).append("\"").append(LINE_BREAK)
                        .append("#endif").append(LINE_BREAK);
            } else {
                langSelectText.append("#include \"").append(defPath.getFileName()).append("\"").append(LINE_BREAK);
            }

            var selFile = Paths.get(toSourceFile(srcDir, "_langSelect" + ".h", generated));
            Files.writeString(selFile, langSelectText.toString(), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            feedbackLogger.fileModificiation(GeneratedFile.always(selFile, langSelectText.toString()));
            feedbackLogger.info("Wrote out the language selector - " + selFile.getFileName());
            feedbackLogger.debug("Finished locale processing");
        }
        finally {
            // put back the same locale as was selected before.
            localeHandler.changeLocale(previousLocale);
        }
    }

    private void localeToCpp(String localeOutputFile, Locale locale, Map<String, String> defaultLocaleMap) throws IOException {
        StringBuilder sb = new StringBuilder(8192);
        sb.append(GENERATED_LOCAL_HEADER).append(" Locale ").append(locale).append(LINE_BREAK);
        sb.append("// Never include directly, always include the langSelect header").append(TWO_LINES);

        localeHandler.changeLocale(locale);
        var allEntries = localeHandler.getUnderlyingMap();
        for(var entry : defaultLocaleMap.entrySet()) {
            var value = (allEntries.containsKey(entry.getKey())) ? allEntries.get(entry.getKey()) : entry.getValue();
            sb.append("#define ").append(asDefine(entry.getKey())).append(" \"").append(value).append("\"");
            sb.append(LINE_BREAK);
        }
        Path path = Path.of(localeOutputFile);
        Files.writeString(path, sb.toString(), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        feedbackLogger.fileModificiation(GeneratedFile.always(path, sb.toString()));
    }

    public static String asDefine(String key) {
        var words = key.split("[^A-Za-z0-9]+");
        return "TC_I18N_" + Arrays.stream(words).map(String::toUpperCase).collect(Collectors.joining("_"));
    }

    private void createTheSourceDirectoriesIfNeeded(Path srcDir, boolean genDir) throws IOException {
        if(genDir) {
            Path genPath = srcDir.resolve("generated");
            if(!Files.exists(genPath)) {
                Files.createDirectories(genPath);
            }
        } else {
            if (!Files.exists(srcDir)) {
                Files.createDirectories(srcDir);
            }
        }
    }

    @Override
    public SketchFileAdjuster getSketchFileAdjuster() {
        return sketchAdjuster;
    }

    protected Map<MenuItem, CallbackRequirement> callBackFunctions(MenuTree menuTree) {
        return menuTree.getAllSubMenus().stream()
                .flatMap(menuItem -> menuTree.getMenuItems(menuItem).stream())
                .filter(mi -> (!isStringEmptyOrNull(mi.getFunctionName())) || MenuItemHelper.isRuntimeStructureNeeded(mi))
                .map(i -> new CallbackRequirement(namingGenerator, i.getFunctionName(), i, localeHandler))
                .collect(Collectors.toMap(CallbackRequirement::getCallbackItem, cr -> cr));
    }

    public static String toSourceFile(Path directory, String ext, boolean generated) {
        Path file = directory.getFileName();
        if (file.toString().equals("src")) {
            // special case, go back one more level
            file = directory.getParent().getFileName();
        }
        if(generated) {
            directory = directory.resolve("generated");
        }
        return Paths.get(directory.toString(), file.toString() + ext).toString();
    }

    protected void generateSource(List<CodePluginItem> generators, String cppFile,
                                  MenuTreeCodeGenerator menuCodeGenerator,
                                  String projectName, CodeVariableExtractor extractor,
                                  Map<MenuItem, CallbackRequirement> callbackRequirements) throws TcMenuConversionException {

        try (Writer writer = new StringWriter(4096)) {
            feedbackLogger.info("Writing out source CPP file: " + Path.of(cppFile).getFileName());

            writer.write(COMMENT_HEADER);
            writer.write("// Generated for %s by TcMenu %s on %s.".formatted(embeddedPlatform, configStore.getVersion(), ISO_INSTANT.format(clock.instant())));
            writer.append(TWO_LINES);

            writer.write("#include <tcMenu.h>" + LINE_BREAK);
            writer.write("#include \"" + projectName + "_menu.h\"" + LINE_BREAK);

            if(fileProcessor instanceof AllInOnePluginFileProcessor) {
                writer.write(LINE_BREAK + "// Each plugin's code now follows here" + TWO_LINES);
            }

            List<HeaderDefinition> includeList = getHeaderDefinitions(generators, List.of());

            // and write out the CPP includes, these are needed for things like adafruit fonts that must only be included once ever
            var includeDefs = extractor.mapCppIncludes(includeList);
            writer.write(includeDefs);
            writer.write(StringHelper.isStringEmptyOrNull(includeDefs) ? LINE_BREAK : TWO_LINES);

            writer.write("// Global variable declarations");
            writer.write(LINE_BREAK);
            writer.write("const " + (usesProgMem ? "PROGMEM " : "") + " ConnectorLocalInfo applicationInfo = { " +
                    getApplicationName() + ", \"" + options.getApplicationUUID().toString() + "\" };");
            writer.write(LINE_BREAK);
            if (hasRemotePlugins) {
                writer.write("TcMenuRemoteServer remoteServer(applicationInfo);");
                writer.write(LINE_BREAK);
            }

            writer.write(extraCodeDefinitions().stream()
                    .map(CodeGeneratorCapable::generateGlobal)
                    .filter(Optional::isPresent)
                    .map(Optional::get)
                    .collect(Collectors.joining(LINE_BREAK))
            );
            writer.write(LINE_BREAK);

            writer.write(extractor.mapVariables(
                    generators.stream().flatMap(ecc -> ecc.getVariables().stream()).collect(Collectors.toList())
            ));

            if(options.getSaveLocation() != ONE_SINGLE_FILE_MENU_MAIN) {
                writer.write(menuCodeGenerator.getRootMenuCode(callbackRequirements, extractor));
            } else {
                writer.write(LINE_BREAK);
            }

            writer.write(LINE_BREAK);
            writer.write("void setupMenu() {");
            writer.write(LINE_BREAK);

            writer.write("    // First we set up eeprom and authentication (if needed)." + LINE_BREAK);
            writer.write(extraCodeDefinitions().stream()
                    .map(CodeGeneratorCapable::generateCode)
                    .filter(Optional::isPresent)
                    .map(Optional::get)
                    .collect(Collectors.joining(LINE_BREAK))
            );
            writer.write(LINE_BREAK);

            writer.write(menuCodeGenerator.generateSetupDeclaration(extractor));

            writer.write("    // Code generated by plugins and new operators." + LINE_BREAK);
            writer.write(extractor.mapFunctions(
                    generators.stream().flatMap(ecc -> ecc.getFunctions().stream()).collect(Collectors.toList()),
                    generators.stream().flatMap(ecc -> ecc.getVariables().stream()).collect(Collectors.toList())
            ));

            if (hasRemotePlugins) {
                menuTree.getAllMenuItems().stream()
                        .filter(menuItem -> menuItem instanceof CustomBuilderMenuItem custom && custom.getMenuType() == REMOTE_IOT_MONITOR)
                        .findFirst()
                        .ifPresent(item -> {
                            try {
                                writer.write(TWO_LINES + "    // We have an IoT monitor, register the server" + LINE_BREAK);
                                writer.write("    " + menuCodeGenerator.getMenuItemAccessor(item) +  ".setRemoteServer(remoteServer);");
                            } catch (IOException e) {
                                feedbackLogger.error("Exception writing cpp file: remote server on IoT monitor");
                                feedbackLogger.error("Exception during write of remote server block", e);
                            }
                        });

                menuTree.getAllMenuItems().stream()
                        .filter(menuItem -> menuItem instanceof CustomBuilderMenuItem custom && custom.getMenuType() == AUTHENTICATION)
                        .findFirst()
                        .ifPresent(item -> {
                            try {
                                writer.write(TWO_LINES + "    // We have an EEPROM authenticator, it needs initialising" + LINE_BREAK);
                                writer.write("    " + menuCodeGenerator.getMenuItemAccessor(item) + ".init();");
                            } catch (IOException e) {
                                feedbackLogger.error("Exception writing cpp file: remote server on EEPROM Authenticator init");
                                feedbackLogger.error("Exception during write of authenticator init block", e);
                            }
                        });
            }
            writer.write(LINE_BREAK + "}" + LINE_BREAK + LINE_BREAK);

            feedbackLogger.info("Finished processing source file.");
            String output = writer.toString();
            Path filepath = Paths.get(cppFile);
            Files.writeString(filepath, output);
            feedbackLogger.fileModificiation(GeneratedFile.always(filepath, output));
        } catch (Exception e) {
            feedbackLogger.error("Failed to generate CPP: " + e.getMessage());
            throw new TcMenuConversionException("Header Generation failed", e);
        }
    }

    private String getApplicationName() {
        if(localeHandler.isLocalSupportEnabled() && isFromResourceBundle(options.getApplicationName())) {
            return asDefine(options.getApplicationName().substring(1));
        } else {
            return "\"" + options.getApplicationName() + "\"";
        }
    }

    public static boolean isFromResourceBundle(String val) {
        return val.startsWith("%") && !val.startsWith("%%");
    }

    public static String removePossibleBundleEscape(String val) {
        if(val == null) return null;
        return (val.startsWith("%%")) ? val.substring(1) : val;
    }

    public static String toUpperWithUnderscores(String in) {
        var splits = in.split("\\W+");
        return Arrays.stream(splits).map(String::toUpperCase)
                .collect(Collectors.joining("_"));
    }

    protected void generateHeaders(List<CodePluginItem> embeddedCreators,
                                   String headerFile, MenuTreeCodeGenerator menuCodeGenerator,
                                   CodeVariableExtractor extractor, String projectName,
                                   Map<MenuItem, CallbackRequirement> allCallbacks) throws TcMenuConversionException {
        try (Writer writer = new StringWriter(4096)) {

            Path path = Path.of(headerFile);
            feedbackLogger.info("Writing out header file: " + path.getFileName());

            writer.write(COMMENT_HEADER);
            writer.write(platformIncludes());
            if(menuCodeGenerator instanceof MenuBuilderTreeCodeGeneratorImpl) {
                writer.write(LINE_BREAK + "#include <tcMenuBuilder.h>" + LINE_BREAK);
            }
            List<HeaderDefinition> includeList = getHeaderDefinitions(embeddedCreators, menuCodeGenerator.headersToGenerate());

            // and write out the includes
            writer.write(extractor.mapIncludes(includeList));
            if(localeHandler.isLocalSupportEnabled()) {
                writer.write(LINE_BREAK + "#include \"" + projectName + "_langSelect.h\"");
            }

            writer.write(TWO_LINES);
            writer.write("// variables we declare that you may need to access" + LINE_BREAK);
            writer.write("extern const PROGMEM ConnectorLocalInfo applicationInfo;");
            writer.write(LINE_BREAK);

            if (hasRemotePlugins) {
                writer.write("extern TcMenuRemoteServer remoteServer;" + LINE_BREAK);
            }
            // and put the exports in the file too
            writer.write(extractor.mapExports(embeddedCreators.stream()
                    .flatMap(ecc -> ecc.getVariables().stream())
                    .filter(var -> var.getApplicability().isApplicable(context.getProperties()))
                    .collect(Collectors.toList())
            ));
            writer.write(TWO_LINES);
            writer.write("// Any externals needed by IO expanders, EEPROMs etc");
            writer.write(LINE_BREAK);
            writer.write(extraCodeDefinitions().stream()
                    .map(CodeGeneratorCapable::generateExport)
                    .filter(Optional::isPresent).map(Optional::get)
                    .collect(Collectors.joining(LINE_BREAK)));
            writer.write(TWO_LINES);

            writer.write(menuCodeGenerator.getHeaderMenuCode(extractor));

            writer.write(TWO_LINES);

            writer.write("// Provide a wrapper to get hold of the root menu item and export setupMenu");
            writer.write(LINE_BREAK);
            writer.write("inline MenuItem& rootMenuItem() { return " + context.getRootObject() + "; }");
            writer.write(LINE_BREAK);
            writer.write("void setupMenu();");
            writer.write(TWO_LINES);

            writer.write("// Callback functions must always include CALLBACK_FUNCTION after the return type"
                    + LINE_BREAK + "#define CALLBACK_FUNCTION" + LINE_BREAK + LINE_BREAK);

            List<CallbackRequirement> callbackRequirements = new ArrayList<>(allCallbacks.values());
            callbackRequirements.sort((CallbackRequirement o1, CallbackRequirement o2) -> {
                if (o1.getCallbackName() == null && o2.getCallbackName() == null) return 0;
                if (o1.getCallbackName() == null) return -1;
                if (o2.getCallbackName() == null) return 1;
                return o1.getCallbackName().compareTo(o2.getCallbackName());
            });

            var callbacksDeclared = new HashSet<String>();
            for (CallbackRequirement callback : callbackRequirements) {
                var header = callback.generateHeader();
                if (!StringHelper.isStringEmptyOrNull(header) && !callbacksDeclared.contains(callback.getCallbackName())) {
                    writer.write(header + LINE_BREAK);
                    callbacksDeclared.add(callback.getCallbackName());
                }
            }

            writer.write(LINE_BREAK + "#endif // MENU_GENERATED_CODE_H" + LINE_BREAK);

            feedbackLogger.info("Finished processing header file.");
            String outData = writer.toString();
            Files.writeString(path, outData);
            feedbackLogger.fileModificiation(GeneratedFile.always(path, outData));
        } catch (Exception e) {
            feedbackLogger.error("Failed to generate header file: " + e.getMessage());
            throw new TcMenuConversionException("Header Generation failed", e);
        }
    }

    private List<HeaderDefinition> getHeaderDefinitions(List<CodePluginItem> embeddedCreators, List<HeaderDefinition> extrasForMenu) {
        // first get a list of includes to add to the header file from the creators
        var includeList = embeddedCreators.stream().flatMap(g -> g.getIncludeFiles().stream()).collect(Collectors.toList());

        // now add any extra headers needed for the menu structure items.
        includeList.addAll(extrasForMenu);

        includeList.addAll(extraCodeDefinitions().stream()
                .map(CodeGeneratorCapable::generateHeader)
                .filter(Optional::isPresent)
                .map(Optional::get).toList());

        if(fileProcessor instanceof AllInOnePluginFileProcessor) {
            includeList = AllInOnePluginFileProcessor.filteringHeaderDefinitions(includeList, requiredSourceFiles);
        }

        return includeList;
    }

    private Collection<CodeGeneratorCapable> extraCodeDefinitions() {
        var extraDefs = new ArrayList<CodeGeneratorCapable>(options.getExpanderDefinitions().getAllExpanders());
        extraDefs.add(new EepromStorageModeCodeCapable(options.getEepromSaveMode()));
        extraDefs.add(options.getEepromDefinition());
        extraDefs.add(options.getAuthenticatorDefinition());
        return extraDefs;
    }

    protected void doSanityChecks() throws TcMenuConversionException {
        boolean eepromAuthenticator = options.getAuthenticatorDefinition() instanceof EepromAuthenticatorDefinition;
        boolean noEeprom = options.getEepromDefinition() instanceof NoEepromDefinition;
        boolean errorFound = false;

        if (!options.getMenuInMenuCollection().getAllDefinitions().isEmpty() &&
                !options.getEmbeddedPlatform().equals(EmbeddedPlatform.RASPBERRY_PIJ)) {
            feedbackLogger.error("Menu In Menu is only supported with embedded Java (Raspberry PI / Linux)");
            errorFound = true;
        }

        if (noEeprom && eepromAuthenticator) {
            feedbackLogger.error("You have selected 'No EEPROM' but then used an EEPROM based authenticator.");
            errorFound = true;
        }

        Collection<MenuItem> allItems = menuTree.getAllMenuItems();

        if (allItems.isEmpty()) {
            feedbackLogger.error("The menu tree is empty, this is not supported, please add at least one item.");
            errorFound = true;
        }

        if (noEeprom && allItems.stream().anyMatch(mt -> mt instanceof ScrollChoiceMenuItem sc && sc.getChoiceMode() == ARRAY_IN_EEPROM)) {
            feedbackLogger.error("You have included a scroll choice item that reads from EEPROM but have not configured an EEPROM.");
            errorFound = true;
        }

        if (!eepromAuthenticator && allItems.stream().anyMatch(mt -> mt instanceof CustomBuilderMenuItem ci && ci.getMenuType() == AUTHENTICATION)) {
            feedbackLogger.error("You have included an EEPROM authentication menu item without using EEPROM authentication.");
            errorFound = true;
        }

        if(options.getSaveLocation() == ONE_SINGLE_FILE_MENU_MAIN && !options.isUseDynamicMenus()) {
            feedbackLogger.error("You have selected to store menu structure in the project main, but have not enabled dynamic menus.");
            errorFound = true;
        }

        if (errorFound) {
            feedbackLogger.error("Please fix any errors before deploying.");
            throw new TcMenuConversionException("Menu conversion errors found");
        }
    }

    public void internalConversion(Path directory, Path srcDir, Map<MenuItem, CallbackRequirement> callbackFunctions,
                                   String projectName) throws TcMenuConversionException {

        try {
            feedbackLogger.info("Starting processing of sketch/main file");
            var inoFile = sketchAdjuster.createFileIfNeeded(feedbackLogger, directory, options);
            feedbackLogger.info("Sketch/main file detected as " + inoFile.getFileName());
            if(options.getSaveLocation() == ONE_SINGLE_FILE_MENU_MAIN) {
                sketchAdjuster.menuTreeInSketch(menuCodeGen.getRootMenuCode(callbackFunctions, extractor));
            }
            sketchAdjuster.makeAdjustments(feedbackLogger, directory, inoFile.toString(), projectName, callbackFunctions.values(), menuTree);
        } catch (IOException e) {
            feedbackLogger.error("Sketch modification failed", e);
            throw new TcMenuConversionException("Could not modify sketch", e);
        }

        // do a couple of final checks and put out warnings if need be
    }

    protected abstract String platformIncludes();

}
