/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include<IoAbstraction.h>
#include<Wire.h>
#include<tcMenu.h>

includes section

// all export definitions



// all menu item forward references.
extern AnalogMenuItem menuTest;
extern BackMenuItem menuBackSub;
extern SubMenuItem menuSub;
extern AnalogMenuItem menuTest;

// all callback functions must have this define on them, it is what the menu designer looks for.
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION callback1(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
