/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <header1.h>

// all define statements needed
#define A_DEFINE 2

// all variables that need exporting
extern VarType varName;

// all menu item forward references.
extern AnalogMenuItem  menuTest2;
extern BackMenuItem  menuBackSub;
extern SubMenuItem  menuSub;
extern AnalogMenuItem  menuTest;
extern EnumMenuItem  menuExtra;
extern const ConnectorLocalInfo  applicationInfo;

// Callback functions always follow this pattern: void CALLBACK_FUNCTION myCallback();
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION callback1(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
