package com.thecoderscorner.menu.editorui.generator.i18n;

import com.thecoderscorner.menu.persist.LocaleMappingHandler;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.Locale;
import java.util.Map;

import static com.thecoderscorner.menu.editorui.generator.core.CoreCodeGenerator.*;

public abstract class I18nCodeGenerator {
    public enum I18nConvertMode {
        LOCALE_PER_FILE,
        PROCESSING_DEFAULT_LOCALE,
        PROCESSING_FIRST_NON_DEFAULT,
        PROCESSING_NON_DEFAULT
    }

    public static final String GENERATED_LOCAL_HEADER = "// TcMenu Generated Locale File, do not edit this file.";
    protected final LocaleMappingHandler localeHandler;

    protected I18nCodeGenerator(LocaleMappingHandler localeHandler) {
        this.localeHandler = localeHandler;
    }

    public abstract void processLocale(Path srcDir, boolean generatedDir) throws IOException;

    protected void localeToCpp(OutputStreamWriter writer,
                             Locale locale,
                             Map<String, String> defaultLocaleMap,
                             I18nConvertMode convertMode) throws IOException {
        if(convertMode == I18nConvertMode.LOCALE_PER_FILE) {
            writer.append(GENERATED_LOCAL_HEADER).append(" Locale ").append(locale.getLanguage()).append(LINE_BREAK);
            writer.append("// Never include directly, always include the langSelect header").append(TWO_LINES);
        } else if(convertMode == I18nConvertMode.PROCESSING_FIRST_NON_DEFAULT || convertMode == I18nConvertMode.PROCESSING_NON_DEFAULT) {
            var ifStatement = (convertMode == I18nConvertMode.PROCESSING_FIRST_NON_DEFAULT) ? "if" : "elif";
            writer.append(LINE_BREAK).append("// Definitions for locale ").append(locale.getLanguage()).append(LINE_BREAK);
            writer.append("#%s defined(TC_LOCALE_%s)".formatted(ifStatement, locale.getLanguage().toUpperCase()));
            writer.append(LINE_BREAK);
        } else if(convertMode == I18nConvertMode.PROCESSING_DEFAULT_LOCALE) {
            writer.append(LINE_BREAK).append("#else // default locale").append(LINE_BREAK);
        }
        var allEntries = localeHandler.getUnderlyingMap();
        for(var entry : defaultLocaleMap.entrySet().stream().sorted(Comparator.comparing(Map.Entry::getKey)).toList()) {
            var value = (allEntries.containsKey(entry.getKey())) ? allEntries.get(entry.getKey()) : entry.getValue();
            writer.append("#define ").append(asDefine(entry.getKey())).append(" \"").append(value).append("\"");
            writer.append(LINE_BREAK);
        }
        if(convertMode == I18nConvertMode.PROCESSING_DEFAULT_LOCALE) {
            writer.append("#endif // locale definitions" ).append(locale.getLanguage().toUpperCase()).append(LINE_BREAK);
        }
    }

    public void addTcLocaleStringMethod(Writer writer) throws IOException {
        writer.append(TWO_LINES);
        writer.append("// Its always better to use getTcLocaleString(string_id) method.").append(LINE_BREAK);
        writer.append("#define getTcLocaleString(x) (x)").append(LINE_BREAK);
    }
}
