name: Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'liberica'
        cache: maven

    - name: Build embedcontrol
      run: mvn -B install -Dgpg.skip=true --file embedControlJavaFx/pom.xml
  
    - name: Build embeddedui
      run: mvn -B install -Dgpg.skip=true --file embeddedJavaDeviceUI/pom.xml

    - name: Build examples
      run: mvn -B install -Dgpg.skip=true --file javaApiExamples/pom.xml

    - name: Build websocket example
      run: mvn -B install -Dgpg.skip=true --file javaApiWebsocketServer/pom.xml
