name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'liberica'
        cache: maven
    - name: Build embedCONTROLCore
      run: mvn -B install --file embedCONTROLCore/pom.xml
    - name: Build tcMenuJavaApi
      run: mvn -B install --file tcMenuJavaApi/pom.xml
    - name: Build tcMenuGenerator
      run: mvn -B install --file tcMenuGenerator/pom.xml
    - name: Build embeddedJavaExample
      run: mvn -B package --file embeddedJavaExample/pom.xml